blank_issues_enabled: true
contact_links:
  - name: Kitewell frontend
    url: https://github.com/Kitewell-lab/frontend
    about: Wallet UI
  - name: Kitewell backend
    url: https://github.com/Kitewell-lab/backend
    about: Horizon API
